apiVersion: v1
kind: Service
metadata:
  name: logstash-netflow-nodeport-service
spec:
  selector:
    app: logstash-logstash
  type: NodePort
  ports:
    - protocol: UDP
      port: 2055
      targetPort: 2055
      nodePort: 30056