apiVersion: v1
kind: Service
metadata:
  name: logstash-netflow-v9-udp
spec:
  selector:
    app: logstash-logstash
  type: NodePort
  ports:
    - protocol: UDP
      port: 4739
      targetPort: 4739
      nodePort: 30058