apiVersion: v1
kind: Service
metadata:
  name: logstash-netflow-tcp
spec:
  selector:
    app: logstash-logstash
  type: NodePort
  ports:
    - protocol: TCP
      port: 2055
      targetPort: 2055
      nodePort: 30057