apiVersion: v1
kind: Service
metadata:
  name: logstash-nodeport-service
spec:
  selector:
    app: logstash-logstash
  ports:
    - protocol: TCP
      port: 9600
      targetPort: 9600
      nodePort: 30016