logstash:
  persistence:
    enabled: true
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "openebs-hostpath"
    resources:
      requests:
        storage: 8Gi
  image: "docker.elastic.co/logstash/logstash-oss"
  logstashConfig:
    logstash.yml: |
      http.host: 0.0.0.0
  logstashPipeline:
    uptime.conf: |
      input { exec { command => "uptime" interval => 30 } }
      output {
        elasticsearch {
          hosts => ["http://elastic.database:9200"]
          user => '${ELASTICSEARCH_USERNAME}'
          password => '${ELASTICSEARCH_PASSWORD}'
          index => "logstash"
        }
      }
    netflow.conf: |
      input {
        udp {
          port => 4739
          codec => netflow {
            versions => [5, 9]
          }
          type => netflow
        }
      output {
        elasticsearch {
          hosts => ["http://elastic.database:9200"]
          user => '${ELASTICSEARCH_USERNAME}'
          password => '${ELASTICSEARCH_PASSWORD}'
          index => "netflow-logstash"
        }
      }
    ipfix.conf: |
      input {
        udp {
          port => 2055
          codec => netflow {
            versions => [10]
            target => ipfix
            }
          type => ipfix
          }
        tcp {
          port => 2055
          codec => netflow {
            versions => [10]
            target => ipfix
            }
          type => ipfix
          }
        }
      output {
        elasticsearch {
          hosts => ["http://elastic.database:9200"]
          user => '${ELASTICSEARCH_USERNAME}'
          password => '${ELASTICSEARCH_PASSWORD}'
          index => "elastiflow-flow-codex-0"
        }
      }
  extraEnvs:
    - name: "ELASTICSEARCH_USERNAME"
      value: elastic
    - name: "ELASTICSEARCH_PASSWORD"
      value: Elastic2Passwordroot